package:
  name: eggs
  version: 1.0.0

source:
  url: https://github.com/TQ-Smith/EGGS/archive/refs/tags/v1.0.0.tar.gz
  sha256: d76feb8b6e30a6c0964e38db9adee3f09aa8599c6d3ea489b9f1cb19daf3c03f

build:
  number: 0
  script: bash build.sh

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - zlib
  run:
    - zlib

test:
  commands:

about:
  home: https://github.com/TQ-Smith/EGGS
  summary: Empirical Genotype Generalizer for Samples 
  description: |
    EGGS is a tool to manipulate genotypes. It can split ms-replicates to 
    multiple VCF files and convert EIGENSTRAT/ANCESTRYMAP files to VCF.
    EGGS is able to introduce various sorts of error, such as sequencing error,
    deamination, and missing genotypes into simulated replicates. EGGS is
    written in C with no dependencies.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/TQ-Smith/EGGS/wiki
  dev_url: https://github.com/TQ-Smith/EGGS

extra:
  recipe-maintainers:
    - TQ-Smith
